### ISSUE TITLE
Kaputter build

### ISSUE THREAD

**Issue by gossie** [philippweikert/gitFridaysThird#5]
Deswegen schlägt der Build fehl:
```
src/ToDoDetails.tsx
[INFO]   Line 15:8:  React Hook useEffect has a missing dependency: 'params.id'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```
Das bedeutet, dass du in der ToDoDetails ein `useEffect` mit leerem dependency Array hast, in deinem Effekt aber etwas verwendet wird, das sich potentiell ändert. Nämlich `params.id`.
So sieht es bei dir gerade aus:
```javascript
useEffect(() => {
    fetch('http://localhost:8080/todolist' + params.id)
        .then(response => response.json())
        .then((toDo: ToDo) => setToDoDetail(toDo))
}, [])
```
Und so müsste es aussehen:
```javascript
useEffect(() => {
    fetch('http://localhost:8080/todolist' + params.id)
        .then(response => response.json())
        .then((toDo: ToDo) => setToDoDetail(toDo))
}, [params.id])
```
Das sorgt dafür, dass immer wenn params.id einen neuen Wert bekommt, das `useEffect` neu ausgeführt wird.

**Comment by philippweikert** [comment]
Oha, ich Troll! Vielen Dank!

André Schreck ***@***.***> schrieb am Do., 10. März 2022,
09:44:

**Comment by philippweikert** [comment]
Ich habe das eingebaut und geht trotzdem nicht... :(

**Comment by gossie** [comment]
Das eine hast du zwar gefixt, aber zwei neue Sachen eingebaut:
```
src/ToDoList/ToDoList.tsx
[INFO]   Line 13:18:  'getTask' is assigned a value but never used  @typescript-eslint/no-unused-vars
[INFO]   Line 14:18:  'getDate' is assigned a value but never used  @typescript-eslint/no-unused-vars
```
